# Generated by Django 2.2 on 2020-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
