# Generated by Django 2.2 on 2020-11-03 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201103_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='core.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
